### ISSUE TITLE
Now that IBM is withdrawing from Swift, is Kitura going to die off?

### ISSUE THREAD

**Issue by bhartsb** [Kitura/Kitura#1497]
## Context and Description
A description of the issue.
As a new user of Kitura, and in light of the news IBM is going to withdraw from Swift I'm thinking about switching to Vapor, as I am very concerned now about putting a lot of effort into building something on a potentially dead end platform.

Thoughts?

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.

### Steps to Reproduce
1) ...
2) ...
etc

### Expected vs. Actual Behaviour
- [ ] Expected to happen...
- [ ] Actually happened...

**Comment by combes** [comment]
I'm wondering this as well.  I've been studying Kitura, working through tutorials,  and planning to build an extensive backend using Kitura but seeing the announcement just this morning I plan to abandon this plan.  I don't trust Vapor either, as that framework does not appear production ready, and is moving so fast it would be difficult to build a maintainable solution. It may also suffer from the version compatibilities as Kitura apparently does.

I'm looking at other solutions now - perhaps Python/Flask, where I can deploy micro services on AWS or other cloud services.  Staying with tried and true solutions appears safest and most maintainable for a server intended for production.

**Comment by xeokeri** [comment]
I've been using Kitura for the past 2 years. Now I'm in the middle of adding new features, while also migrating to Vapor. It certainly isn't a one-to-one process. Would also like to know the remaining lifecycle of Kitura.

**Comment by bhartsb** [comment]
Looks like IBM has abandoned Swift and Kitura:  https://www.theregister.co.uk/2019/12/20/ibm_istio_knative_tensorflow_should_be_under_open_governance/
It would be nice if Apple took up Kitura.

**Comment by dannys42** [comment]
I rather like Kitura.  Are there any others in the community willing to join in keeping it going?

**Comment by xeokeri** [comment]
I would be more than pleased to keep it going.

**Comment by diuming** [comment]
IBM market oriented.

**Comment by michzio** [comment]
I think it should be community developed. Nice if Kitura and Vapor will interchangeable in case of packages and just possible to have two different coding styles

**Comment by crspybits** [comment]
I've been using Kitura for several years now. And am also wondering where this is going to go.

**Comment by dannys42** [comment]
I don't know where else to discuss this, but I'm considering just forking the project and doing what I can to help with pull requests.  @crspybits and @xeokeri what do you think?  Interested in helping to keep Kitura going?  Any others?

**Comment by xeokeri** [comment]
@dannys42 @crspybits I’m all for it. I’ve been using Kitura for my project for a few years. I tried refactoring to allow switching to another. Though, I was not happy with the end results. At this time, I would rather address fixing issues within Kitura, as well as adding features to it. Instead of jumping ship. Kitura was more stable than the other, too.

**Comment by crspybits** [comment]
Thanks for reaching out @xeokeri. This is a large endeavor. For me, I have two concerns. I still want to continue work on my own personal project (currently, using Kitura). I emphasize *personal* here, as in I have limited time and no backing for server-side swift. Second, I'd have to figure out if my employer allows this. Like some employers, mine puts some limits on what I can do independently.

I'm curious about why your refactoring didn't work out. Sounds like you were trying to use Vapor. I haven't used others, but that's a definite possibility for me-- e.g., that I'd switch over to using, say, Vapor.

What would be great is if there could be some kind of other corporate backing behind Kitura. IBM has put a great deal of effort into this.

**Comment by xeokeri** [comment]
@crspybits For me, yes, it was Vapor. I fully converted the entire project over to Vapor 3, but had to wait for Vapor 4 to support my needs, that Kitura already did. I have 3 branches, other than master for my personal project. I kept both the Kitura and Vapor in parity, in separate branches. Although, the Vapor wasn’t as stable or reliable, to be honest. I also prefer the way Kitura works over Vapor. I need command line, web, and various parts. Vapor 3 wasn’t intended to work that way. Kitura was. Vapor 4, only in the last 48 hours, did I get a response to my issue posted to Vapor for the defects/docs/issues I was having to make it less forced to work as a web server always.

**Comment by dannys42** [comment]
@crspybits I can totally sympathize.  I'm in a very similar situation with limited time and it's a purely personal endeavor.  I've tried using Perfect and Vapor, but I found Kitura is just much cleaner, functional, and consistent in behavior.  Vapor does seem to have a lot of community backing, but it just goes a little crazy with futures and I find it very difficult to work with.

I'd hate to see Kitura go away, so I was hoping to at least help keep it up-to-date with newer versions of swift and help with pull requests.  I'm not sure I'd be able to contribute significantly to any new features or issue requests.  But I figured an active maintainer is better than none especially if the community is willing to support it.

**Comment by dannys42** [comment]
FYI there seems to be a few others interested on the Slack channel.  I'm going to make the fork, but I think to be safe trademark-wise we need a new name for the project.  Any ideas?

**Comment by xeokeri** [comment]
Maybe something with a play on the original name? Something prefixed with Kin, as in gold? Just a thought.

**Comment by pckrishnadas88** [comment]
what is the current status of this framework?

**Comment by dannys42** [comment]
@pckrishnadas88 I'm attempting to get this project to be community managed.  If you or anyone else is interested in contributing, please let me know!

**Comment by crspybits** [comment]
@dannys42 Hey! Have you had contact with the IBM folks? It seems better if this can keep going under the present Git repos, IMO. It would give continuity to the location and branding of the code. Like I said before, I have limited time, but I am interested in this project, and could make sporadic contributions. E.g., previously I made a PR with the Kitura Credentials.

**Comment by pckrishnadas88** [comment]
> @pckrishnadas88 I'm attempting to get this project to be community managed. If you or anyone else is interested in contributing, please let me know!

I found only this framework promising in the swift world for web development in the enterprise world. Do you know why IBM dropped this project? People will contribute to the code as long as they feel there is someone really good leading the project.

**Comment by fabrijp** [comment]
Fenix? - new name :) @dannys42

**Comment by bhartsb** [comment]
Phoenix unless you want it spelled fenix.

**Comment by dannys42** [comment]
Hello all,

I have great news!  Kitura is going to be a community project from now on.  Please see [https://forums.swift.org/t/kitura-is-now-a-community-project/39199](https://forums.swift.org/t/kitura-is-now-a-community-project/39199) for the official announcement and discussions.  Don't hesitate to reach out if you have any interest in helping to shape the project in any way.

Thanks for the name contributions, but just to set the record straight there is no trademark issue after all, so Kitura will be keeping its name.  Sorry for any confusion I may have caused.

Thanks all and happy coding!

**Comment by crspybits** [comment]
Very nice!! :). Congratulations!

**Comment by fouadhatem** [comment]
Can we close this now?

**Comment by bhartsb** [comment]
Fine by me.  Thanks.
