### ISSUE TITLE
Migrate kitura.io project from IBM-Swift org to Kitura.org

### ISSUE THREAD

**Issue by dannys42** [Kitura/Kitura#1521]
I'm waiting to gain control of the kitura.io domain before making this transition to reduce the chance of breaking the website, since it relies on GitHub pages.

**Comment by dannys42** [comment]
Technically this should belong to the [kitura.io](https://github.com/IBM-Swift/kitura.io) repository, but since that's in the IBM-Swift org, I can't do that yet.

**Comment by fouadhatem** [comment]
I don't think they should have a problem handing it over. Do you? Have you mentioned this to them during your discussions?

**Comment by dannys42** [comment]
kitura.io repository is migrated.  But it looks like the kitura.io domain is expired.  I don't know if we're getting it back.  So I'm closing this issue and created [Issue 1523 - Migrate all docs to kitura.dev](https://github.com/Kitura/Kitura/issues/1523) instead.
