### ISSUE TITLE
Minor version bump for all projects

### ISSUE THREAD

**Issue by dannys42** [Kitura/Kitura#1524]
I think in order to ensure everything builds cleanly, I’m going to have to do a version bump to all the repos that are referencing other Kitura projects.  The issue is that the versions currently existing are referencing the IBM-Swift org.  And I think SPM may get confused about duplicate projects (i.e. treating IBM-Swift/xyz as a separate project from Kitura/xyz and then getting confused about duplicate providers).  I think this may show up in dependencies of dependencies.

Anyway, as I have to version bump everything, I’m thinking of just bumping everything to x.y.200 for several reasons:

- There is no code change, so a patch-level version update makes sense
- Starting off on the same patch version will make it easier to identify problems due to a project that is still referencing the old repo
- It will also make it easier to update Package.swift files for developers using Kitura to specify x.y.200 as the minimum version, rather than having to know the specific "x.y.z" version of each package that has the corrected orgs.

**Comment by mbarnach** [comment]
I like the idea of publishing a new patch, but why 200? Apart from the obvious, that it will be the same number everywhere, why going to 200 and not +1?

**Comment by dannys42** [comment]
That's really the main reason... to identify pre-"Kitura org" references more easily.  And 200 just to be sure it's far enough from any existing patch versions.
