### ISSUE TITLE
[Question]Is it possible set Kitura-NIO as default in Xcode 11.6

### ISSUE THREAD

**Issue by diuming** [Kitura/Kitura#1533]
## Context and Description
I try to use `Kitrua` again.(good framework struct, easy to use , useful documents and examples, ...)
I don't have any idea to set `Kitura-NIO` as default in Xcode.
could someone give me advice?
thx.

### Environment Details
macOS 10.15.6
Swift 5.2.4
Xcode 11.6

![Screen Shot 2020-10-21 at 9 41 20 AM](https://user-images.githubusercontent.com/39903550/96662935-22798e80-1382-11eb-92ee-ef94ef85a306.png)
![Screen Shot 2020-10-21 at 9 41 37 AM](https://user-images.githubusercontent.com/39903550/96662940-260d1580-1382-11eb-908c-6f22e7cdb2a5.png)

**Comment by dannys42** [comment]
Unfortunately there isn't a good way to do this at this time.  It's rather ugly, some people have created a custom fork and pointed their project at that.

**Comment by diuming** [comment]
@dannys42 got it.
