### ISSUE TITLE
[Issue]Swift-Kuery-SQLite (Release 2.0.200) in Xcode

### ISSUE THREAD

**Issue by diuming** [Kitura/Kitura#1535]
## Context and Description
Swift-Kuery-SQLite (Release 2.0.200) in Xcode

### Environment Details
macOS 10.15.6
Swift 5.2.4
Xcode 11.6

![Screen Shot 2020-10-22 at 8 41 28 AM](https://user-images.githubusercontent.com/39903550/96804739-6d5adb00-1442-11eb-9198-2a440271be58.png)

**Comment by dannys42** [comment]
@diuming would you mind sharing more of the text of the logs?  Also can you share the dependencies you're specifying in Xcode?  I'm curious why there's a 2.0.201..<3.0.0 requirement there.  It should start from 2.0.200.

**Comment by diuming** [comment]
@dannys42 
where can i find logs?

current added packages
---
![Screen Shot 2020-10-23 at 1 37 37 PM](https://user-images.githubusercontent.com/39903550/96960417-fa7e5c80-1534-11eb-8a76-fe435fc35eaa.png)


add package `Up to Next Major`
---
![Screen Shot 2020-10-23 at 1 27 05 PM](https://user-images.githubusercontent.com/39903550/96959992-d1110100-1533-11eb-8937-33b0ce36c6cb.png)
![Screen Shot 2020-10-23 at 1 27 58 PM](https://user-images.githubusercontent.com/39903550/96960008-d8d0a580-1533-11eb-9c71-5ea112d69b61.png)

add package `Exact`
---
![Screen Shot 2020-10-23 at 1 26 39 PM](https://user-images.githubusercontent.com/39903550/96960066-fe5daf00-1533-11eb-9858-f1df57bfbb44.png)
![Screen Shot 2020-10-23 at 1 26 10 PM](https://user-images.githubusercontent.com/39903550/96960070-00277280-1534-11eb-8c8f-a2d5f853da8b.png)

add package `Up to Next Minor`
---
![Screen Shot 2020-10-23 at 1 32 14 PM](https://user-images.githubusercontent.com/39903550/96960217-644a3680-1534-11eb-8a70-6be9836a363a.png)
![Screen Shot 2020-10-23 at 1 33 03 PM](https://user-images.githubusercontent.com/39903550/96960221-6613fa00-1534-11eb-8577-4d60f776bbe6.png)

**Comment by dannys42** [comment]
@diuming Thank for the additional info.  You are correct, it looks like the root cause was this line:

```swift
.package(url: "https://github.com/Kitura/Swift-Kuery.git", .branch("master")),
```

I've fixed it and it should hopefully be working for you now.

**Comment by diuming** [comment]
@dannys42 thanks for help.
