### ISSUE TITLE
Kitura.dev should point to valid Slack group

### ISSUE THREAD

**Issue by AnyCPU** [Kitura/Kitura#1542]
I know there is a lot of issues on updating docs, but I think it is the most important now.
Kitura.dev points to http://slack.kitura.io/, but Kitura.IO is not our friend.
It is a disappointing thing and the project loses new contributors. 

@dannys42 Happy New Year!

**Comment by dannys42** [comment]
Oh wow, so sorry about that.  Thanks for mentioning it!

**Comment by dannys42** [comment]
@AnyCPU Would you mind confirming that the link is now working correctly for you?

**Comment by AnyCPU** [comment]
@dannys42 yes, it does.
