### ISSUE TITLE
upgrade from 0.1.0 to 0.2.1, kitura command totally mess up

### ISSUE THREAD

**Issue by choonghansoong** [Kitura/Kitura#1553]
## Context and Description
A description of the issue.

### Environment Details
macos 11.3.1, Swift version  and Xcode version if on macOS.

Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.4.0

Xcode 12.5

### Steps to Reproduce
$brew upgrade ibm-swift/kitura/kitura

$kitura --version (not working)
$kitura init (not working, need project name now)
$kitura init TestApp
$cd TestApp
$swift run

will hang at this point
[89/104] Compiling KituraNet ConnectionUpgrader.swift

**Comment by choonghansoong** [comment]
obsolute project

**Comment by dannys42** [comment]
Hi @choonghansoong , I recently re-wrote the kitura cli.  I'll make a note to update the documentation to match, but you can find some of it in the [kitura-cli README](https://github.com/Kitura/kitura-cli/).  For now there is very minimal functionality in the command-line app. I'm not sure why you're hanging though.

**Comment by choonghansoong** [comment]
Thanks for the update.
